language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "RYQemsIceB/t+elIqLZM4tXPrUUHSLfwCRX3zwdzKGSPQtYx+ccHoNOmSnbutrwuheAhZhb8PGOp166Z2D9GTXNSF9iS8t3iqAr9G9E9bTkcPOOesZzHm1YZU2fds8rGm+hGBlSY3A5i7Al0tMXY5M6TcJbg50nqR+g429G0Ihm8EqXWZ9GmFQQ+Jw2qx8kpakDnwJEZn+YJwtdxNDVqZ2UBPwBCOpWoQu13EeH5VQ/W2r+KezBKma5kkCl03dvJeekariwAElyl6BpsbJKTfTNoOf2ML9551Megn7N/XYhXOYxL8fhRnCDG6A3XCHVttVsZiyLUZII7iOdGLkbLOvjq+DInTUvHKzMhMIcs5naDOZLRXeTteS/xtKTYcTNSaQ6J9FVRrB/4tRPaAdKaRumn/gLkyPybYL/vXps97usDsv6NsHJGMMdQaCFIEtJhzu3nZygEdHQG+2R8HPskBJFgDFVz9q1OJR7YiDJrjFI7jnr37HA3+xwHE6zfpA8NsC6zOUaeHNRWFin4a/IcUctzfZWcLw4+Neer4pprU3TlxmBY8pXCkj5OdEpgNjbDqK04knehDn6d/B75NGg9s/P9uG9Gw1UU8uaMe7KJVhKsV4mAKTZMqbBDo+vKgayPJ7eTahgf0NNqKCA0wQ35hV+rWaThA8eaeaxdF48ZEMc="
    - secure: "HBflk4KPMKddUOM3r1gdRycSXbWdH+eW7RS6z2l5EQwayvUdeI7lggfYbJQ8RlkfJlt8uOC2KwTv8bTrlNdlkF+qVj5Khl3k/PjhmHpVcRNdqmmXMz516DAtmy4TVChMZsO1MpfdurLtVJ1CAytCljXaiJfrMkspv2m6EabyC6C4pwzSP6OTJwa3SEF6ajEc19hsCEF1IPJt2m9812ElFBvyidKCd514syHHCy734qw/w/ZOL+GgaBY9qS59GUct9U6B8bn/OrwZYOCSFDoM+0+9WtkK+j4WUjv5KrciY/mfBvwNVJtncrUyvBXw2mWEqZhmARn8wgFaLb1XAKTI/gO0uryae2R2CHtwJ4EWZUN7G7swXDrK9FtOPjxr2Qk4ualjkxaYbDC15B1Isid4sgafnK2mhfEFIUkGyUnD1rxwrQxZa4kQJ92LEJReDaai9I3guOQO0iZEMVkx1/mz9MMaDulWhowyC+5iu9BcXs+MKh9T30h48oiWOXJXuwugRDhiqBGN/CnsIZvKdcGI7MMkeEsLNln59VP7fe5ktlVGSf/vsJt9WtaA7vLvW/QxRicxcmOXe/ubeMB8/rPsWdAwiY6kmw1auIEY+vvHUyyV7CmxIfilQ8YavHueeG/EGuznuq4Sh9gh32w36e4Ye0tAlwSCTN5ZAUhzw5qYSWQ="

script: mvn install

after_success: mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken="${PROJECT_TOKEN}" -DapiToken="${API_TOKEN}"

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: never
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  slack:
    secure: eMZgS79kzSH6opY2sSJhrYdTg0jLB/JzLEvQFcn6xoDtek3/WjWWg4+M8sYv/qPqwzY3jeJ0vxd8SIwcgBJkgOHVJqvmqxWV49/F8EOENaDU+oWo5vUUh8GvM1e+B/4wZd14PbD6w9m4qs1gIAUcPECE21p0KDtvN/VYnH+96LI=

sudo: false
